hash-format = "sha256"

[[files]]
file = ".git/COMMIT_EDITMSG"
hash = "24694d8a4565e033ccf7468a3beda68e50051e18207b804612f6e21f6d225bd1"

[[files]]
file = ".git/HEAD"
hash = "e96b2cc9c75cfabeb2ac176b747212acd417372936b7c4c89e9d53b76c7be645"

[[files]]
file = ".git/config"
hash = "5d752ed1e36ee60084826b3e8cd40b179e542368e1bb37d0b38d6ed6e14d7d03"

[[files]]
file = ".git/description"
hash = "85ab6c163d43a17ea9cf7788308bca1466f1b0a8d1cc92e26e9bf63da4062aee"

[[files]]
file = ".git/hooks/applypatch-msg.sample"
hash = "0223497a0b8b033aa58a3a521b8629869386cf7ab0e2f101963d328aa62193f7"

[[files]]
file = ".git/hooks/commit-msg.sample"
hash = "1f74d5e9292979b573ebd59741d46cb93ff391acdd083d340b94370753d92437"

[[files]]
file = ".git/hooks/fsmonitor-watchman.sample"
hash = "f3c0228d8e827f1c5260ac59fdd92c3d425c46e54711ef713c5a54ae0a4db2b4"

[[files]]
file = ".git/hooks/post-update.sample"
hash = "81765af2daef323061dcbc5e61fc16481cb74b3bac9ad8a174b186523586f6c5"

[[files]]
file = ".git/hooks/pre-applypatch.sample"
hash = "e15c5b469ea3e0a695bea6f2c82bcf8e62821074939ddd85b77e0007ff165475"

[[files]]
file = ".git/hooks/pre-commit.sample"
hash = "f9af7d95eb1231ecf2eba9770fedfa8d4797a12b02d7240e98d568201251244a"

[[files]]
file = ".git/hooks/pre-merge-commit.sample"
hash = "d3825a70337940ebbd0a5c072984e13245920cdf8898bd225c8d27a6dfc9cb53"

[[files]]
file = ".git/hooks/pre-push.sample"
hash = "ecce9c7e04d3f5dd9d8ada81753dd1d549a9634b26770042b58dda00217d086a"

[[files]]
file = ".git/hooks/pre-rebase.sample"
hash = "4febce867790052338076f4e66cc47efb14879d18097d1d61c8261859eaaa7b3"

[[files]]
file = ".git/hooks/pre-receive.sample"
hash = "a4c3d2b9c7bb3fd8d1441c31bd4ee71a595d66b44fcf49ddb310252320169989"

[[files]]
file = ".git/hooks/prepare-commit-msg.sample"
hash = "e9ddcaa4189fddd25ed97fc8c789eca7b6ca16390b2392ae3276f0c8e1aa4619"

[[files]]
file = ".git/hooks/push-to-checkout.sample"
hash = "a53d0741798b287c6dd7afa64aee473f305e65d3f49463bb9d7408ec3b12bf5f"

[[files]]
file = ".git/hooks/update.sample"
hash = "8d5f2fa83e103cf08b57eaa67521df9194f45cbdbcb37da52ad586097a14d106"

[[files]]
file = ".git/index"
hash = "0e4fc09f50b9cca80582eb4892e6f76f508fef2cc389aeb6e158a2c647ea72ca"

[[files]]
file = ".git/info/exclude"
hash = "6671fe83b7a07c8932ee89164d1f2793b2318058eb8b98dc5c06ee0a5a3b0ec1"

[[files]]
file = ".git/logs/HEAD"
hash = "a03b5ed3365d2863cb9b569708bc37b87f526b5e57cdb30168c98e29e5b94c02"

[[files]]
file = ".git/logs/refs/heads/Builder_Pack"
hash = "444536e8791032b3adf941b5f1a2359a6f99fc616300ead8edeaa8b8ac23593b"

[[files]]
file = ".git/logs/refs/heads/main"
hash = "2f735300aeaaa44e7a49f0446d23ac3199dc56402966156303823e5d0bc8676d"

[[files]]
file = ".git/logs/refs/remotes/origin/Builder_Pack"
hash = "540c284405aa4e45cce8325860e7c4d8eb02e0b9d71245f5b3404722fcc27b3b"

[[files]]
file = ".git/logs/refs/remotes/origin/HEAD"
hash = "a8bd55704382349ed01937ee94b265d96b27f9ef402bccc9243fa85a8dde5c69"

[[files]]
file = ".git/logs/refs/remotes/origin/main"
hash = "1123aab33d8f4274d71221a89a785118bcffc47fb8d8727eb7f1c3db320fadf7"

[[files]]
file = ".git/objects/16/e28cc139ee6f149c0d02ac66a4498f92abce9f"
hash = "d29a894eebe119e8dca51f06cf16257038f5ff12f7a610f0b761f74895963fbb"

[[files]]
file = ".git/objects/17/c9cab6b1978326bf29455207ba69492c9ef7b6"
hash = "31f0a93fdb772966877a6402cc5f5df31c462fe235c4c8240b1f34cedf516a98"

[[files]]
file = ".git/objects/45/10f8c2d21a7e0c2b8075955692ad004e373833"
hash = "c52d2a1ff3911c4b70fbfc6f814771aa61db49a7f69038001195f66d76f06624"

[[files]]
file = ".git/objects/5d/f84b1549698b8c7c037f0fe12256d281c1826f"
hash = "16a3980922261e3c194ada452b45e58e25d797abd2bc8dee154987f5269e0253"

[[files]]
file = ".git/objects/5f/1576d2e4375c8335e8afc99ff286161ec63859"
hash = "0d4136219a35d621c1eea99abb12c1ddd735bfc1998cb4e6de1884dde5335786"

[[files]]
file = ".git/objects/7d/ed6b5302176d74420a3de49c61b453a1258ac8"
hash = "cc53c3735d4eb01366ecdbf3b2bbcf70da2eba1aac885c575c0f20b70a829a01"

[[files]]
file = ".git/objects/7e/ea8384eb0d912f5999ddc6f574f4615a945663"
hash = "c79932add49a9b6660f15c2cae96f683f8c31666ccd702750a0ada62d766678e"

[[files]]
file = ".git/objects/85/be949120fc2780a94404df27e10145385ffd1d"
hash = "2646eafe4f2b800ce883e2e58329892e0995e59cc5af494e31dfcaec90fde145"

[[files]]
file = ".git/objects/ad/ce6250f9717abdac19f2365513a203ae10a4ae"
hash = "593ec64b37c9116bfd8e5f048b5ec19b883f37e5789a67846945a2a734d1195a"

[[files]]
file = ".git/objects/b9/7926d304f29c30b757dc7b16f40bac2b658466"
hash = "6eed0e23f8de4793f0014a7af73c595a4e4bf7f709bdc264c57102c2e15d6abe"

[[files]]
file = ".git/objects/c3/adb816850f5485141c767b80d7539224babe08"
hash = "9762101bb4fcb1935d5e537bf5b8b1e6610c84666e5b26674b30d2aa7d61e671"

[[files]]
file = ".git/objects/cb/5f2716adcb1950753474ca045393a3bdd72ecb"
hash = "6c61ed48341538ba0ae78aad7d738ab80d358e05693ec4deba0d6ace5d724721"

[[files]]
file = ".git/objects/d0/8564446467e8e35f8c5554c18b3a7d2179c943"
hash = "508beab7e25c33856edf12a161d634484f9515115566ad27dd69d73759867512"

[[files]]
file = ".git/objects/d9/56943ffaf36ea6eaa0b36f6dafd8bc871ac1d9"
hash = "bbb36a688f665e0650f433f4dfb0f28c7ca81911c910467f78710dea29c53ff3"

[[files]]
file = ".git/objects/ef/73c50435fa79e11c23348eb9a2b3083b2fb17c"
hash = "02e755cdf4a2cf3342cacdd7bfba94e8cf6d4df618c773746e0ebdf0d0494a7d"

[[files]]
file = ".git/objects/pack/pack-0cf6251e53e60cce64d7a72c7ae0891e2399fc9e.idx"
hash = "87938c09952f9ecb48017f7daabbd0e1f90b739ec15ab13bb9cdfaff8133a7ee"

[[files]]
file = ".git/objects/pack/pack-0cf6251e53e60cce64d7a72c7ae0891e2399fc9e.pack"
hash = "c162475fc3e77eba30f0f679334bee16becf18e3479566e94aef9d365e5b7b0b"

[[files]]
file = ".git/packed-refs"
hash = "743c4dd9d9f2fd2ba936c0fa26ed9bde10f404fa556adf827e6e3e62abeeec9d"

[[files]]
file = ".git/refs/heads/Builder_Pack"
hash = "bfd9cd9ada14d8213c2fdec2ad5b452a10acc2805cced126b757595b342e30fa"

[[files]]
file = ".git/refs/heads/main"
hash = "69e233cd1adb6bbd7cc29b602fd090771edcbeca739a520fb284048d9602bfbe"

[[files]]
file = ".git/refs/remotes/origin/Builder_Pack"
hash = "bfd9cd9ada14d8213c2fdec2ad5b452a10acc2805cced126b757595b342e30fa"

[[files]]
file = ".git/refs/remotes/origin/HEAD"
hash = "2bb6a24aa0fc6c484100f5d51a29bbad841cd2c755f5d93faa204e5dbb4eb2b4"

[[files]]
file = ".git/refs/remotes/origin/main"
hash = "69e233cd1adb6bbd7cc29b602fd090771edcbeca739a520fb284048d9602bfbe"

[[files]]
file = ".gitignore"
hash = "38c84b8b3818698ffea8bdd2b66782794bac0b84b13e8cc48bf3599a0536fd30"

[[files]]
file = ".packignore"
hash = "b753fab8d84388bb348d6d431a48bbdc77fc3d561d14f967914ee7b9e237c7e8"

[[files]]
file = "manifest.json"
hash = "5cfa13df5d7cc7d5e05172a6fc03b776d974608161509abd96b5fb2f181ce95a"

[[files]]
file = "modlist.html"
hash = "5aade42cf487bd69d151fe2ec90fd35055bd33c3a2c762940bff0cc4b289fddb"

[[files]]
file = "overrides/mods/hydrogen-fabric-mc1.17.1-0.3.jar"
hash = "598f6168244467220f37e9a5a07a5ba59af5a0df0edf5ba13a44c7ee9b02c1e1"

[[files]]
file = "overrides/mods/inspecio-1.1.0+1.17.jar.disabled"
hash = "c7ec27c5cbe68679e02b36d78e260b39f1ada48a5f45ce48365b1a4edb485d19"

[[files]]
file = "overrides/mods/modmanager-1.1.1-alpha+1.17.jar"
hash = "f8d13af85845a50b842b1eb7d7ecde121713445e40891cee11a15f1fed1dbbfd"

[[files]]
file = "overrides/mods/mtape-mc1.17.1-1.4.0.jar"
hash = "5a54c6ecc5ed7186bf0dc2fb13d9b57c9502b35865c02beb828efd2da60f917d"

[[files]]
file = "overrides/options.txt"
hash = "996c890d22d8be8095e0880a323f1b5e1a7f3c75f47c360b745d8f5aa48d501a"
