hash-format = "sha256"

[[files]]
file = "icon.png"
hash = "062f6c5a9ee276deee39f9afeeb7a3594364eb8ee514048caf17296dcc068519"

[[files]]
file = "options.txt"
hash = "1b4baf2937aec8536758a380baab4ce0170030f5be54cc07336a2ea960a4914b"
