hash-format = "sha256"

[[files]]
file = "icon.png"
hash = "41bee2503da522e20f7082cbb6fe03172c71fde701ac5e1e1980dce11f944606"

[[files]]
file = "options.txt"
hash = "1b4baf2937aec8536758a380baab4ce0170030f5be54cc07336a2ea960a4914b"
