hash-format = "sha256"

[[files]]
file = "icon.png"
hash = "d52689411d25bc2e4dad98bca829af65e50dda7504875297a125df4325277363"

[[files]]
file = "options.txt"
hash = "1b4baf2937aec8536758a380baab4ce0170030f5be54cc07336a2ea960a4914b"
