hash-format = "sha256"

[[files]]
file = "config/apotheosis/adventure.cfg"
hash = "38c424c8f20d503db1eb9f7fac7c023b2a16b2d83198bbad5bfa6669c40ff749"

[[files]]
file = "config/cofh_core-client.toml"
hash = "308bb7e904e226b1af363cef2a85260c188c5f466de51a214a888250c1a99aa6"

[[files]]
file = "config/delightful-common.toml"
hash = "007756ce780efcaf00f66aa41fbcf3747dbf392e8f385cba2cd776b99dd8c8a4"

[[files]]
file = "config/do_a_barrel_roll-client.toml"
hash = "3ef96f21daafd1d188c44c6e9531ffff008385d0e0950b1e29d5e91075dd3a52"

[[files]]
file = "config/quark-common.toml"
hash = "31b7e91c848e21dbc58b816642459c0f0cdf51e688e3f810f89ad494aab8fce6"

[[files]]
file = "config/tetra.toml"
hash = "93b7e2fac95deb963b7331b03a91701539f53fc90f39b93358c55bd8e56a3fbf"

[[files]]
file = "icon.png"
hash = "2fc8d71d81ad2f6e28a5038981087c0660c52f5ff4a528d9a2a6cebf81e3cd89"

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "dcb41bc03af0f90df2bf6162c83c07d95a97403757a200460a4bbd7ef70b18fa"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "7961a7438ef8b4c33f7b356319bd338bb8db592da949e846be54314610dbeb79"
metafile = true

[[files]]
file = "mods/apotheosis.pw.toml"
hash = "27f7d8717daf931f1295fac200904bdfee985936a427b4ef4a286ddd34308594"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1be3c626f8c8e445e57444f2559dc590edafc75b6c8c18d4599703dbc614a7e8"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "c0737aed914926fae77727ed67cfd46c1504fc1ce5a5b704e3669a3307898507"
metafile = true

[[files]]
file = "mods/art-of-forging-a-tetra-addon.pw.toml"
hash = "4277c9ea1350361ff82e1a67bbebc42ac8f8ac6ccd3a7085c3972a1d5d66b388"
metafile = true

[[files]]
file = "mods/attribute-tooltip-fix.pw.toml"
hash = "269abd72e2f31644749f603562d164e806e1b75c3066e80b9697ab8e22210303"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "55e7b06eb9bb8d3a8d993cb9232c90c3054acad3ab1f51c06fb712720a7669df"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
hash = "75745dee1d0a29cfa70f3fc7dd7b8638daed99f413bcf8f1ad7521faca2de805"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "2264acfbd388023f4c11b06b18e1a8b79b2b078e9fbf4cc38b31e4cb31c653dd"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f6cbf049bf3d857ff70736e3cae7cb3b3cf42fe01142e7b38c1520e9209428f2"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "679ff153724bf9aec89645d48765f108fd75362e387b6e33e920e6ec5f33fba6"
metafile = true

[[files]]
file = "mods/blossom.pw.toml"
hash = "eda8b86afa03baec7a0ff28ba9a98ebd329a5474f2e4514c8a00ec4239c9bed4"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "e7a31bca2c89624f212365c8ba63364652ae7163af1b0d6effafb4f1b27c2d42"
metafile = true

[[files]]
file = "mods/butchercraft.pw.toml"
hash = "dc7bc9d6340e7a1248fd68f7b8e1459acbee48f518f9c4b6db9cef35eda31c90"
metafile = true

[[files]]
file = "mods/chest-cavity-forge-port.pw.toml"
hash = "4ce1a53e44a8855a2173a614d10efe733186499f19105af96733efb68779750b"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "d42a44515e657e67431cb042727db14f697b6d80c88c1da5fbe4c8afce738d29"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "775ba9db8af593510ab38e497e4bed1aa5dcd7cae8cdd1d6a2dbe693c28de8fa"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "3c6e9f14e71e880b00b3c61a34cb9f7d3e65641b9aa5f6a549a1e257248224ec"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "e23bf79734607ac718d7ef76a45eac20387af0ce0f30b3d0ea40d31245671290"
metafile = true

[[files]]
file = "mods/combat-roll.pw.toml"
hash = "c4dacebc1c335c4e4d140f80978b60f0e799a7cbd79520fef166af84270e0653"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "55fe6ab593105e257757c69572113ff554a92a1407899f4a8170e72d50e712bf"
metafile = true

[[files]]
file = "mods/continents.pw.toml"
hash = "49d330937c995cb37ad2e070ab1d6b2c13f5ab9be95720d1f99a137e419c62c3"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "f5c0acdd29ffba387899edcc2890e7c3c555c8f481ee80864d1e2300349d6184"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
hash = "11b9e1462b5ebdbd13c92e44b4cfaa873d93435d77af721be1321d4a102b9e8c"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "d7a48770616551eb9a38bd8d60a7a72dc96ecf84e264cb8486cf6d8ad4070ef1"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "b73ce95376567a9876985d12308d478d2cce342e0d540a3b8fd1403f42dc948b"
metafile = true

[[files]]
file = "mods/createtweaker.pw.toml"
hash = "c274a1edf73ba543a33f29e5540be16238da403b344e32c322c9d88e87a2597a"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "61ce95654a33c10e7c54c121f720c3bb58af8d99b2ba9521ae08556f629b6cc1"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "661100014e376d46f904a15a2acd72084acceb771a2daae06fde211fec2259b7"
metafile = true

[[files]]
file = "mods/ctov-farmers-delight-compat.pw.toml"
hash = "74549af849da49934eb9e8b548ea2d2bc035095ad189d7dbb8ba42639166e59c"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "0c793add13628f1ebaea6843fe54c77e4e2a5c1e1ca88efe67612b4dcbf318a5"
metafile = true

[[files]]
file = "mods/curios-quark-oddities-backpack.pw.toml"
hash = "6b1c0608c9b365ae455695092be4f86e314907124f7c9856d012fc7cad0c8068"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "de029c0f0d7e48adde50029e115c012e7a0f37128d71b0d4808c3347f08ddd1c"
metafile = true

[[files]]
file = "mods/debugify-reforged.pw.toml"
hash = "592477120db7c09e06649d2cee7d7ca98018c3d53a2214b87020fa34ae704af2"
metafile = true

[[files]]
file = "mods/delightful.pw.toml"
hash = "8efc269dee36af1fbcba2a0d29f697b710af95c11dcc466a1f4c514c24a2a47d"
metafile = true

[[files]]
file = "mods/devworld.pw.toml"
hash = "66972fe5aac4e1668123c20a6d779c78c26c0c0f6cb5f1bd1d7bb22ead66e760"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "06c469593efe0864c59c9c490b7debe2d91bab2c317fb30014401e0a5422d0fa"
metafile = true

[[files]]
file = "mods/dynamic-view.pw.toml"
hash = "a32278774d6d46fc54a56e80e3110748040797776950035b208105c61f4264b4"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "32919ba2d15d55cec37bc8759064e1983e9a917c3ccfe25c4ad880cbf0a7026b"
metafile = true

[[files]]
file = "mods/entity-collision-fps-fix.pw.toml"
hash = "a2eabebaf6a16fb2b13952c5256169c610002998ce519118577e55d7307b1d94"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "905b8553a85833b28d6932db4882e584cfd4717d3fcf90b4da94a73b718a9a3a"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "45195222bc6c21bb60602680a564149990736c0b516efa1aa2f8bf75b163c9f5"
metafile = true

[[files]]
file = "mods/farming-for-blockheads.pw.toml"
hash = "0eef33260f4dcb2da3898bc9854655281423f347eaa192068d4f4f2313a6e461"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
hash = "26793eb76fb5e048eaa4e8589c8f59df9457241208afd10b641e45b3ebe81aca"
metafile = true

[[files]]
file = "mods/fastsuite.pw.toml"
hash = "33b060b044446221d8aed52e115330c112619b1baf637f9a494db54b77fe77d2"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
hash = "61aacdeb320bcad34a2d30f27ba85176d0cbb5e9b84c478c545b102ddedc7e07"
metafile = true

[[files]]
file = "mods/fixmyspawnr.pw.toml"
hash = "0c56bd81d012abdeac41386ac918e14f437e6f09e5bb28e6d91ccef2e88384ad"
metafile = true

[[files]]
file = "mods/fx-control.pw.toml"
hash = "a14c91e039fba0e24cd31d7aee5a22bbd28e1b05d65964ad9c9e5c5c1adc931e"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.pw.toml"
hash = "7bfc6fd8a94e02e289c31c8500215abdfbbb29f92535ebceeb7a76ffb7efb251"
metafile = true

[[files]]
file = "mods/ibe-editor.pw.toml"
hash = "c229b9c7d45c3305b4bd06f2c882b02d6dc074b7c2a466f3395554322169ae03"
metafile = true

[[files]]
file = "mods/immersiveengineering.pw.toml"
hash = "b185e27a51765a6c34548350227e468d108615db2c91cd96966da3a469b28932"
metafile = true

[[files]]
file = "mods/in-control.pw.toml"
hash = "fb0819262a796b32174ad2b9b7d2f026b6aa2c1044dd24ff0f21a26769506a52"
metafile = true

[[files]]
file = "mods/infectum.pw.toml"
hash = "c16b30aca5245ac49540b90ebe629ce4753d956bb323cf1b99a4e1dd10f95c22"
metafile = true

[[files]]
file = "mods/ironchests.pw.toml"
hash = "9d15fb9c800e8db3250fb4ae013e5dad8137491fba49d2497f2f49463dbc05af"
metafile = true

[[files]]
file = "mods/it-shall-not-tick-(isnt).pw.toml"
hash = "5243c6465689fb09a1d797dd4775e2b466d1b92abf70cbd3620610814cfe7d84"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "37843a77555f43048f0fe9351bbed76aa4b46b1d7d8f941a940f07a32e34dc2b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "fde0369eaad4e6f507b0e1d238b131877b9a291deff0715c9f1b5fb397aa176a"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "3771e470a987db1273b97e7e58e290ffd626f3835c27c99c434097fafa232cb4"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "fb8cdad0427a6eb005fef56c5262aa72774b97363348a7fa9c7ffbd38f67d1ea"
metafile = true

[[files]]
file = "mods/kube-utils.pw.toml"
hash = "54764a923b065d86171f30b61580cbfe4e9f2090958bbbf652311935675efc32"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "e19de1461835a018573b0b064da0f476f5b5ba1b80b014566a9dfc8703144ff2"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.pw.toml"
hash = "6ffd1ef0b2ac6e0d310ce32af0f943f014937620f7046433772b0b3f3585e2f6"
metafile = true

[[files]]
file = "mods/log-begone.pw.toml"
hash = "f6b691a9e4a78c96c62fd8a9f46eebc6ebdfb47b01e6d4a37639a2d939666586"
metafile = true

[[files]]
file = "mods/lootjs.pw.toml"
hash = "81efad0010eb13d11f576ee779f6a89f42de4b05899d26536342573c7a4f8c6a"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "4df53639528c1d5752ccdb38fda14dbd9c5f60ec441e7b3a457a2918a09ee5fd"
metafile = true

[[files]]
file = "mods/mahou-tsukai.pw.toml"
hash = "e3b9d711182ecd029ccf9aed0954b8a37e9b9742b309d24909446a0e82a93531"
metafile = true

[[files]]
file = "mods/morejs.pw.toml"
hash = "59e9970f526b5fa0442adbaedd7bb53f9092bea36e7a5942014f905e0bf3ae5f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9cba22bdbc8c89d44438b1e22ae677f7d6bf1c7f1adecfff2760427f2d974dee"
metafile = true

[[files]]
file = "mods/mutil.pw.toml"
hash = "10ee486fbdd37ff8122078eef834d60d65b7fb1ca43a35fc0e41aae8e71f2417"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "327b293c048b78ea3d3cbc7a39fbf16e476f503d7e10bdc45e9df4122876539d"
metafile = true

[[files]]
file = "mods/no-nv-flash.pw.toml"
hash = "a8781ae0c71cb6b7aeb414e9939788ca50100d446159a3e54faae1722fb4d06b"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "4f7281f41989118c6b2a441c182ed577d6e71f9f93d4368533bd6f5fc6ea3694"
metafile = true

[[files]]
file = "mods/nutritional-balance.pw.toml"
hash = "ae6bf77d8298be06cb6d95e707f2337ff49f4d8737a81a3b61dc270d0d05a5ee"
metafile = true

[[files]]
file = "mods/packages.pw.toml"
hash = "2f1f61091f4716ba6fe48ae4b94824f169d460e7f5fcaaf7838248a2aeafc1a6"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "8895f6fc1d8d8280539f3e381f3b0316d912600d7a8dda216ce83466abaa5aee"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "663a3f2f25983b9a40a941bce124de46129313b3c632cbff6bb9858976106b44"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "997b0a2ee714d012e405bee97cb806f182378a9a31cf2dac2afeb960a31922fd"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "b31228db5fa6f653fe3067c8abd614b103d45fc4e326657fa6a41ce9b4d348b5"
metafile = true

[[files]]
file = "mods/playerrevive.pw.toml"
hash = "b39d73e8ec9b4b15726560c1d906f3a3412f93d30ca63bf4ccd63da646e5e7a4"
metafile = true

[[files]]
file = "mods/pluto.pw.toml"
hash = "d3685a6f5ff1e2b32979192e068b9c1f5e04fac73e147a5a0c2f0a3fa8093b2b"
metafile = true

[[files]]
file = "mods/powershot.pw.toml"
hash = "aee8aafb953d17e8ef9c2f82f09a9b082d97d9eb8aab8bb50f919d55ec144bce"
metafile = true

[[files]]
file = "mods/quark-oddities.pw.toml"
hash = "90560337b2ad996abe8d1fb74130972b83ff9954d1742bbcc1a8588aa5628528"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "2fe0d8d6b9dc02c1579dc65910ac26f046db707c2ed0813e9b347a7320e5ffd5"
metafile = true

[[files]]
file = "mods/radon.pw.toml"
hash = "c997b01c920a40f34096a6bd172c9f9d78b77b9ce9e80ad965bf6f4d081847b1"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6a89bd5046fa6e39cd3a0c62bd1be4e5b13f7a58bb070fc12e05cbe7bd23d572"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "e6eeba74394d495851373bbc97b8940f96896a225366f9b0e65a3c301e4d8ab7"
metafile = true

[[files]]
file = "mods/rubidium.pw.toml"
hash = "960a369b2d51d9bcda7353187e9379d51621a902388de5782ca7a7d2bf1da2a4"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "2a3627e70bfae32d33e2b8fb694410db7caa96d51a9a9dfe46ff98a033f63935"
metafile = true

[[files]]
file = "mods/serverconfig-updater.pw.toml"
hash = "f540ae946ff56136c405fb4baafffbbb9882d76afe151c7a431a3a98420f08a6"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "4f237850c9cc02e448b67301ad1d235c12c27d9cc687badc37557d2138777f35"
metafile = true

[[files]]
file = "mods/some-assembly-required.pw.toml"
hash = "4a610cc1e50e46bc9c3f83355620e039c0fa443baed5b687093a182b7f36d3c6"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "dcce713339e8439339648019b3d7781414bbbc31ad21e2be52366bbebb374c4a"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
hash = "2b72e6219824ab27aed8006746109ff4c449e1cb4d5ca6cd9a17a05495e2c03d"
metafile = true

[[files]]
file = "mods/suggestion-tweaker.pw.toml"
hash = "3db733e1cad2b465e3d924b2b7e372dc063ecbd013ffa0b22225f27dfdad4e77"
metafile = true

[[files]]
file = "mods/tellme.pw.toml"
hash = "b495e226ec531bccf07f6bd6c022dce36a13af72aaea2ba76e2f22992c2f1d7b"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "4abb977e75acf39451b0d74890b3e9c42674ca865c1c73dcab216f5d2b5a3c7f"
metafile = true

[[files]]
file = "mods/tetra.pw.toml"
hash = "29cb5b33d82d045486651230f372e2412b087d97c5f1edc239cbd82e2b53d029"
metafile = true

[[files]]
file = "mods/tetratic-combat.pw.toml"
hash = "3b06afd1e63e37b80d4f769a15e327b9a573ab88e44766c464ae031079805676"
metafile = true

[[files]]
file = "mods/textrues-rubidium-options.pw.toml"
hash = "364657be8f0aee667dbd73cbd8a95ff63437422484075440042033c398dcdcd8"
metafile = true

[[files]]
file = "mods/thermal-cultivation.pw.toml"
hash = "79bb000c750a9f954eeaf389798c82bb6b9b5562a238960a7e3921811ea8c783"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "afd9b2b50903a0b5d73fd367349db2f492dbc07c79721e8ed0b9c1ba87870eb1"
metafile = true

[[files]]
file = "mods/torchmaster.pw.toml"
hash = "f846c5299cc77e44928c1c13574e9abafd619042f0f83a4a874f70fcd8c6e3ac"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "957ff865b8349be0fb4a9fd7b2ef08e844ffd870113b0772fcfa74c67d4c53fc"
metafile = true

[[files]]
file = "mods/world-stripper.pw.toml"
hash = "bf3f6418846c6f580f228c741e7169a6e0aa85967f537a6e48eb91149a802b5e"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "719da66ac6adbf00ace4a021f1bfcd6aca271b16caa40629de9e73a79b844905"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "5ef2b4759a2ef2c4d5c092656a3ad70b624327dd270c734599147a86b4c2bfad"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "d9abcfc042a281afcc89dbf6bd55e0f9b9e1ae15d7865cfe86cc5d3eabdad77a"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "bbf5eb83507d5b572177e9a4867328fa9ac3dec5f348722717a6243e8636b1f8"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "730bae79446575b4d6937182e132c35a5132e4edf7c145d034c82b43e568d0f8"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "876d6d97b9865951980144a235511c2b74ef1fff4e592e1090332cee23055413"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "c8c4d642c29438cbe0cc822489b7ed98e8ef18dad417bb6a2b09656a330bbceb"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "3e3083db8ddba94ecff7ce045a760a30019c5163720cffcf105ef11a11c56048"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "88aa2f0e23517ef50e745f384b75a45875a77933c5e06c1f6dd1943174af515c"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "c760b48e6c1a2fbc88ef0202a6d4e9559b61a280df2f374a9081edf3bb18bd8b"
metafile = true

[[files]]
file = "serverconfig/immersiveengineering-server.toml"
hash = "f23d8f966de41fa2055822f2cd9401fbbb42bffdbef081c10ebe9ca0f654f5fb"
