hash-format = "sha256"

[[files]]
file = "manifest.json"
hash = "cda3ae3d4014b4f9a1e7e98bfd532c922c512d2e7f3159c1a68092503354c3c1"

[[files]]
file = "modlist.html"
hash = "5aade42cf487bd69d151fe2ec90fd35055bd33c3a2c762940bff0cc4b289fddb"

[[files]]
file = "overrides/mods/hydrogen-fabric-mc1.17.1-0.3.jar"
hash = "598f6168244467220f37e9a5a07a5ba59af5a0df0edf5ba13a44c7ee9b02c1e1"

[[files]]
file = "overrides/mods/inspecio-1.1.0+1.17.jar.disabled"
hash = "c7ec27c5cbe68679e02b36d78e260b39f1ada48a5f45ce48365b1a4edb485d19"

[[files]]
file = "overrides/mods/modmanager-1.1.1-alpha+1.17.jar"
hash = "f8d13af85845a50b842b1eb7d7ecde121713445e40891cee11a15f1fed1dbbfd"

[[files]]
file = "overrides/mods/mtape-mc1.17.1-1.4.0.jar"
hash = "5a54c6ecc5ed7186bf0dc2fb13d9b57c9502b35865c02beb828efd2da60f917d"

[[files]]
file = "overrides/options.txt"
hash = "996c890d22d8be8095e0880a323f1b5e1a7f3c75f47c360b745d8f5aa48d501a"
