hash-format = "sha256"

[[files]]
file = "icon.png"
hash = "2d4bca2dff90ec74138c7bb6f647216bf793e17e2571d425ddc727086953c112"

[[files]]
file = "options.txt"
hash = "1b4baf2937aec8536758a380baab4ce0170030f5be54cc07336a2ea960a4914b"
