name = "Shattered_Stars"
author = "Kenja__"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a514f6be2c51158c3fb5278e86c53441a3a47ad494cf52ce2b4394d7d0b9468f"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
