name = "Shattered_Stars"
author = "Kenja__"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb1643e73682cfc04630022be675819c263b71cb2cc48d3431b952e2c526d4d6"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
