name = "shstar-forge-1.18"
author = "Kenja__"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87737f4cb1d0e9f9ccd302b56e841e081cf5a18aa041b6a45fbbc0202c367cc1"

[versions]
forge = "38.0.16"
minecraft = "1.18"
