name = "shattered_stars"
author = "Kenja__, Strange-Bird-of-the-Moon"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bba0d1f2cb924e052e3f2cefd13679c0d72fa9c59d8f96e4d356b5ac4e232fa"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
