name = "shstar-forge-1.18"
author = "Kenja__"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16f4bfcb23d90db394e37ca7917017d4cde0c4a5d7e6771da277af36036c9496"

[versions]
forge = "38.0.16"
minecraft = "1.18"
