name = "shattered_stars"
author = "Kenja, Strange-Bird-of-the-Moon"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7931c3ebaffa57240fbef8f0678abcedb861ff458227d34d7159b373cf45dc"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
