name = "Shattered Stars"
author = "Kenja__"
version = "0.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e589467bcbae1ee42dc20a39b2a53a4caca6bdc22907a4281f257b2edbd259bd"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
