name = "shattered_stars"
author = "Kenja__"
version = "0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "286a1cc2109518d59457c5d3494e69df8d2156a525aa4a7f140f86a8534f0b04"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
