name = "shattered_stars"
author = "Kenja__, Strange-Bird-of-the-Moon"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94d1b882b8a10177de9d2ce982fc625a62e827266a0a0415957134a9d89bf9e8"

[versions]
forge = "43.2.6"
minecraft = "1.19.2"
