name = "shattered_stars"
author = "Kenja__"
version = "0.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e37c3a54952275235ca7cec78d5fca27d40200438a72318802b6e2b1e9d5de56"

[versions]
fabric = "0.12.8"
minecraft = "1.17.1"
