name = "shattered_stars"
author = "Kenja__"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea720b2aba1355cdecad036b6202ebf717ac2c826d680a6e782a8d37d3739ff0"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
