name = "shattered_stars"
author = "Kenja__, Strange-Bird-of-the-Moon"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70d9282739b1bce077b86d3babb3dc22d94ba8dedf07dd367ffe3787b12b3819"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
