name = "Shattered_Stars"
author = "Kenja__"
version = "0.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7105a52b5da955313c35646a6be5fa91e586d47d84a1cc63b417432c50e9c92"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
