name = "shattered_stars"
author = "Kenja__, Strange-Bird-of-the-Moon"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "668053c668f6474ee1b548d7fb67e1115990c9fa8bb1a4fb71391b9bde78f4aa"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
