name = "shattered_stars"
author = "Kenja__"
version = "0.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e81074b770d8e7e9921f9a7e1b894f2fb310ec84e4cdc238da35bb4c0f763d"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
