name = "Shattered_Stars"
author = "Kenja__"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "300837026e6c9c7ca674d1e9e5a3ce7768a423a29e4ea3ee7f3990a84712ea58"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
