name = "Shattered Stars"
author = "Kenja__"
version = "0.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f8d8e02fc3357470ff2bcc99d244dd8023d30e80f35d985dbf98bfa07c5f10f"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
