name = "shstar-forge-1.16.5"
author = "Kenja__"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a80f230edf2098658cec33aa85b71a92ab604950d898ff032aeb443da3adc5"

[versions]
forge = "36.2.19"
minecraft = "1.16.5"
