name = "Shattered_Stars"
author = "Kenja__"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a62c049b2bd303f87184695fb6689cc32aa2cd64316f4d97b0f0978c64ee70"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
