name = "shattered_stars"
author = "Kenja__"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37ccb7b50e6ea0f53a7c4543212eb183cceab44a2dcab5aff7501fa0f8c1d11c"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
