name = "Shattered_Stars"
author = "Kenja__"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1fbaf349ca3b4660fe5701b4d28690c2e06c17eeb69c9905078dda62c5157ad"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
