name = "shattered_stars"
author = "Kenja__, Strange-Bird-of-the-Moon"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c13bf08c9af1e65f3113c79661cfc9944d593742103ced951252c4c4a5c6927"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
