name = "Shattered_Stars"
author = "Kenja__"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb899144a6aa487e3d20e87156bfdd1e46c567bb192013d7baf56c43c9f6f31c"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
