name = "shattered_stars"
author = "Kenja__"
version = "0.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f22f9334138e68dd9fd0ad8b2121a4d915d6a603df20d36e865c9cf7938bd2c"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
