name = "Advanced Compass"
filename = "AdvancedCompass-fabric-1.2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3496/85/AdvancedCompass-fabric-1.2.6.jar"
hash-format = "murmur2"
hash = "2456142994"

[update]
[update.curseforge]
file-id = 3496085
project-id = 461424
