name = "Better Sodium Video Settings Button"
filename = "bsvsb-2.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3487/563/bsvsb-2.0.4.jar"
hash-format = "murmur2"
hash = "2947878852"

[update]
[update.curseforge]
file-id = 3487563
project-id = 437443
