name = "Cammie's Combat Tweaks"
filename = "combattweaks-1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3516/570/combattweaks-1.5.jar"
hash-format = "murmur2"
hash = "3055404317"

[update]
[update.curseforge]
file-id = 3516570
project-id = 535617
