name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.17.1-v1.23.1+build.703.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3498/67/carpet-tis-addition-mc1.17.1-v1.23.1+build.703.jar"
hash-format = "murmur2"
hash = "2167790804"

[update]
[update.curseforge]
file-id = 3498067
project-id = 397510
