name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.17.1-v1.24.0+build.742.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3516/21/carpet-tis-addition-mc1.17.1-v1.24.0+build.742.jar"
hash-format = "murmur2"
hash = "4245311755"

[update]
[update.curseforge]
file-id = 3516021
project-id = 397510
