name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.54+v211117.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3528/977/fabric-carpet-1.17.1-1.4.54+v211117.jar"
hash-format = "murmur2"
hash = "3923353070"

[update]
[update.curseforge]
file-id = 3528977
project-id = 349239
