name = "Carpet"
filename = "fabric-carpet-1.17.1-1.4.51+v211028.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3507/168/fabric-carpet-1.17.1-1.4.51+v211028.jar"
hash-format = "murmur2"
hash = "4015566653"

[update]
[update.curseforge]
file-id = 3507168
project-id = 349239
