name = "Chunky Pregenerator (Fabric)"
filename = "Chunky-1.2.124.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3426/914/Chunky-1.2.124.jar"
hash-format = "murmur2"
hash = "1345517952"

[update]
[update.curseforge]
file-id = 3426914
project-id = 433175
