name = "Collective (Fabric)"
filename = "collective-fabric-1.17.x-1.63.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3529/17/collective-fabric-1.17.x-1.63.jar"
hash-format = "murmur2"
hash = "1739125160"

[update]
[update.curseforge]
file-id = 3529017
project-id = 526606
