name = "Data Reload"
filename = "datareload-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/637/datareload-1.1.jar"
hash-format = "murmur2"
hash = "3481057682"

[update]
[update.curseforge]
file-id = 3443637
project-id = 521450
