name = "GrabcraftLitematic"
filename = "grabcraft-litematic-1.17.1-fabric0.36.1-0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3445/758/grabcraft-litematic-1.17.1-fabric0.36.1-0.5.jar"
hash-format = "murmur2"
hash = "3015329285"

[update]
[update.curseforge]
file-id = 3445758
project-id = 411741
