name = "Grim Statues"
filename = "statues-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3445/194/statues-1.0.1.jar"
hash-format = "murmur2"
hash = "723137116"

[update]
[update.curseforge]
file-id = 3445194
project-id = 520827
