name = "Multiworld (Fabric)"
filename = "Multiworld-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/759/Multiworld-1.1.jar"
hash-format = "murmur2"
hash = "3690386463"

[update]
[update.curseforge]
file-id = 3414759
project-id = 511765
