name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-3.7.2+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3522/731/notenoughcrashes-3.7.2+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "167407146"

[update]
[update.curseforge]
file-id = 3522731
project-id = 353890
