name = "Prefab - Fabric"
filename = "prefab-fabric-2.1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3481/68/prefab-fabric-2.1.6.jar"
hash-format = "murmur2"
hash = "3783428380"

[update]
[update.curseforge]
file-id = 3481068
project-id = 438696
