name = "Revive"
filename = "revive-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3481/242/revive-1.0.0.jar"
hash-format = "murmur2"
hash = "85576011"

[update]
[update.curseforge]
file-id = 3481242
project-id = 533879
