name = "Sync (Fabric)"
filename = "sync-mc1.17.x-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3452/111/sync-mc1.17.x-1.2.jar"
hash-format = "murmur2"
hash = "2760344323"

[update]
[update.curseforge]
file-id = 3452111
project-id = 515365
