name = "Sync (Fabric)"
filename = "sync-mc1.17.1-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3524/557/sync-mc1.17.1-2.0.jar"
hash-format = "murmur2"
hash = "3698519092"

[update]
[update.curseforge]
file-id = 3524557
project-id = 515365
