name = "William Wythers' Overhauled Overworld"
filename = "WilliamWythersOverhauledOverworld-1.7.1(1.17.x).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3523/433/WilliamWythersOverhauledOverworld-1.7.1(1.17.x).jar"
hash-format = "murmur2"
hash = "2911902123"

[update]
[update.curseforge]
file-id = 3523433
project-id = 490686
